export const errorString = {
  firstnameMissing: 'First name is required.',
  lastnameMissing: 'Last name is required.',
  emailMissing: 'Email is required.',
  passwordMissing: 'Password is required.',
  confirmPasswordMissing: 'Confirm password is required.',
  passwordLengthExceed: 'Password must be at least 6 characters long.',
  passwordNotMatch: 'Passwords do not match.',
  emailExist: 'This email is already registered.',
  usernameMissing: 'Username is required.',
  dateOfBirthMissing: 'Date of birth is required.',
  numberMissing: 'Phone number is required.',
  AgeLimitRestriction: 'You do not meet the age requirement.',
  numberWrong: 'Invalid phone number format.',
};
